version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    ports:
      - "5001:5001"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  
    networks:
      - elk-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /Users/saima/Desktop/logs/test.log:/usr/share/logs/test.log:ro
    depends_on:
      - elasticsearch
    command: filebeat -e
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
